version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: issuebombom
      POSTGRES_PASSWORD: issuebombom
      POSTGRES_DB: nowlisten-server-local
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

networks:
  nowlisten-server-network:
    external: true
